;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname ex28) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp")) #f)))
; The problem statement specifies
; how the number of attendees depends on the ticket price.
(define (attendees ticket-price)
  (- 120(* (- ticket-price 5.0) (/ 15 0.1))))

; The revenue is exclusively generated by the sale of tickets,
; meaning it is exactly the product of ticket price and number of attendees
(define (revenue ticket-price)
  (* ticket-price (attendees ticket-price)))

; The cost consists of two parts: a fixed part ($180)
; and a variable part that depends on the number of attendees. 
(define (cost ticket-price)
  (+ 180 (* 0.04 (attendees ticket-price))))

; Finally, profit is the difference between revenue
; and costs for some given ticket price
(define (profit ticket-price)
  (- (revenue ticket-price)
     (cost ticket-price)))

(profit 1.00) 
(profit 2.00) 
(profit 2.90) 
(profit 3.00)
(profit 4.00)
(profit 5.00)